import{S as p,i}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&e(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function e(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const m=a=>{const o="47393342-0b139bb531c328d079618af8b",s=new URLSearchParams({key:o,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(e=>{if(!e.ok)throw new Error(`Error: ${e.status}`);return e.json()}).then(e=>e.hits).catch(e=>(console.error("Failed to fetch photos:",e),[]))},u=a=>a.map(({webformatURL:o,largeImageURL:s,tags:e,likes:t,views:r,comments:n,downloads:c})=>`<li class="gallery-item" >
            <a href="${s}" alt="${e}" title=""/>
            <img src="${o}" alt="${e}" class="gallery-image">
            <div class="gallery-container">
            <p class="item"><span class="item-text">Likes</span> <span>${t}</span></p>
            <p class="item"><span class="item-text">Wiews</span> <span>${r}</span></p>
            <p class="item"><span class="item-text">Comments</span> <span>${n}</span></p>
            <p class="item"><span class="item-text">Downlods</span> <span>${c}</span></p>
            </div></a>
            </li>`).join("");let d=new p(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});const g=document.getElementById("search-form"),f=document.getElementById("gallery"),l=document.querySelector(".loader");g.addEventListener("submit",async a=>{a.preventDefault();const s=document.getElementById("search-input").value.trim();if(!s){i.info({title:"",message:"Please, enter a search term!",messageColor:"#FAFAFB",backgroundColor:"#EF4040",position:"topRight"});return}l.style.display="block";try{const e=await m(s);e.length?(f.innerHTML=u(e),d.refresh()):i.info({title:"",backgroundColor:"#EF4040",messageColor:"#FAFAFB",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(e){console.error("Error fetching data:",e),i.error({title:"Error",message:"Something went wrong. Please try again later.",messageColor:"#FAFAFB",backgroundColor:"#EF4040",position:"topRight"})}finally{l.style.display="none"}});
//# sourceMappingURL=index.js.map
